Bug: #43
Addressed warnings as per the following:

- Operator-related warnings dealt with, with one note:
	// dcmtk v3.5.4 has header file for DcmMetaInfo that includes an
	// assignment operator, but implementation file does not implement it.
	// Since SWIG references the header file, I suspect that the signature
	// it expects can't be matched with the compiler-generated assignment
	// operator, and that's why the linker balks (unresolved reference).
	// For now, I'll ignore the DcmMetaInfo assignment operator
- ..\..\OFFIS\dcmtk\dcmdata\include\dcmtk\dcmdata\dcdict.h(54): Warning(205): CPP #error ""DCM_DICT_DEFAULT_PATH is not defined via osconfig.h"".
	○ Innocuous; since this warning is generated only during the wrapping phase, andr doesn't halt compilation of dcmtk library. Probably a header file referencing problem.
- ..\..\OFFIS\dcmtk\dcmnet\include\dcmtk\dcmnet\dimse.h(858): Warning(322): Redundant redeclaration of 'DIMSE_SubOpProviderCallback',
	○ Innocuous; dcmtk problem.
- ..\..\OFFIS\dcmtk\dcmdata\include\dcmtk\dcmdata\dcelem.h(53): Warning(403): Class 'DcmElement' might be abstract, no constructors generated,
	○ Innocuous; DcmElement is abstract.
- ..\..\OFFIS\dcmtk\dcmdata\include\dcmtk\dcmdata\dcobject.h(146): Warning(403):  method 'clone' might not be implemented
	○ Innocuous; DcmObject is abstract.
- OffisDcm_dcmnet_interop.i(9): Warning(451): Setting a const char * variable may leak memory.
	○ Fixed, this was caused by an improper modifier const being applied
- Warning(845): … C# code won't handle pending exceptions because of the lack of canthrow attribute.
	○ Fixed; this was caused by the typemaps that handle std::string& for the "in" typemap not having the canthrow attribute set even though it might throw exceptions.